SELECT FOOD_TYPE,REST_ID, REST_NAME, FAVORITES
FROM REST_INFO
WHERE (FOOD_TYPE, FAVORITES) IN (
    SELECT FOOD_TYPE, MAX(FAVORITES)
    FROM REST_INFO
    GROUP BY FOOD_TYPE
)
ORDER BY FOOD_TYPE DESC

#FOOD_TYPE을 REST_INFO로 하면 틀린다.
#이유는 REST_INFO는 식당명을 반환하는데 GROUP BY의 결과로 식당명은 맨 위의 값을 가져오기 때문이다.