SELECT CAR_ID,
CASE 
    WHEN CAR_ID in (
        SELECT CAR_ID
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
        WHERE '2022-10-16' BETWEEN START_DATE AND END_DATE 
     ) THEN "대여중"
    ELSE "대여 가능"
END AS AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
GROUP BY CAR_ID
ORDER BY CAR_ID DESC



#1ST 시도
#전체 - > GROUP BY로 묶고, END_DATE 최대일 뽑기
#END_DATE가 10-16 이전이면 "대여가능 "
#2ND 시도
#전체 GROUP BY로 묶고,
#SELEC문에서 WHERE로 START_DATE와 END_DATE사이에 2022-10-16, GROUP BY로 묶어서 COUNT(*)
#인지 확인