WITH TMP AS (SELECT CAR_ID
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
WHERE START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
GROUP BY CAR_ID
HAVING COUNT(*) >= 5)
# 기간 안 5번 이상 빌린 자동차 아이디

SELECT MONTH(START_DATE) AS MONTH ,CAR_ID, COUNT(*) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
WHERE START_DATE BETWEEN '2022-08-01' AND '2022-10-31' AND CAR_ID IN (SELECT CAR_ID FROM TMP)
GROUP BY CAR_ID, MONTH(START_DATE)
ORDER BY MONTH(START_DATE), CAR_ID DESC