-- 코드를 입력하세요


SELECT ICECREAM_INFO.INGREDIENT_TYPE, SUM(A.PRICE) AS "TOTAL_ORDER"
FROM ICECREAM_INFO
JOIN (SELECT FLAVOR, SUM(TOTAL_ORDER) AS PRICE
     FROM FIRST_HALF
     GROUP BY FLAVOR
     ) A
ON ICECREAM_INFO.FLAVOR=A.FLAVOR
GROUP BY INGREDIENT_TYPE